### ISSUE TITLE
implement javax.microedition.lcdui.Alert in HTML

### ISSUE THREAD

**Issue by mykmelez** [andreasgal/j2me.js#535]
The *javax.microedition.lcdui.Alert* class is a screen that displays a simple alert along with some buttons and sometimes a throbber. The version in the reference implementation is unattractive and slow, but it's used by a number of midlets, including those that mostly show their own screens; so we should implement an attractive and performant version in HTML.

**Comment by marco-c** [comment]
Fixed by #819.
