### ISSUE TITLE
java.lang.RuntimeException: RangeError: repeat count must be non-negative

### ISSUE THREAD

**Issue by marco-c** [andreasgal/j2me.js#550]
This happens when you run j2me.js on a phone with no SIM.
The error is in the *pad* function in *util.js*, because the values that we're trying to pad (mobileInfo.network.mcc and mobileInfo.network.mnc) are undefined

**Comment by yxl** [comment]
Fixed by https://github.com/andreasgal/j2me.js/pull/936
