### ISSUE TITLE
JSR-075 FileConnection TCK tests intermittently time out

### ISSUE THREAD

**Issue by mykmelez** [andreasgal/j2me.js#817]
The JSR-075 FileConnection TCK tests intermittently time out on Travis. I've seen it happen 2-3 times now. Here's an example from a recent merge commit (after the tests passed on the branch being merged):

>     com.ibm.tck.javax.microedition.io.file.FileConnection.Rename#test0019 passed
>     (IOException or SecurityException thrown if connection is opened on a non-existent host)
>     TESTLOG: Operation trace:
>       Opened connection on a non existent host: file://TCKBogusHost/TCKFileSystem/test
>       Expected IOException thrown
>     
>     [warning] [phantom] Casper.waitFor() timeout
>     FAIL "All Tests Passed" did not appear in the page in 15000ms
>     #    type: uncaughtError
>     #    file: /home/travis/build/andreasgal/j2me.js/tests/fs/automation.js
>     #    error: {"message":"\"All Tests Passed\" did not appear in the page in 15000ms","name":"TimedOutError"}
>     #    stack: not provided
>     [info] [phantom] Step _step 36/36 http://localhost:8000/main.html?main=com.ibm.tck.client.TestRunner&args=-noserver&jars=tests/tests.jar&logConsole=web,page (HTTP 200)
>     [info] [phantom] Step _step 36/36: done in 21383ms.
>     FAIL 7 tests executed in 21.416s, 6 passed, 1 failed, 0 dubious, 0 skipped.     
>     
>     Details for the 1 failed test:
>     
>     In /home/travis/build/andreasgal/j2me.js/tests/fs/automation.js
>       fs tests
>         uncaughtError: "All Tests Passed" did not appear in the page in 15000ms
>     make: *** [test] Error 1
>     
>     The command "make test" exited with 2.
>     
>     Done. Your build exited with 1.

**Comment by marco-c** [comment]
Maybe we can just increase the 15s timeout
