### ISSUE TITLE
Cannot input  Chinese characters in text editor with an input method

### ISSUE THREAD

**Issue by yxl** [andreasgal/j2me.js#835]
@marco-c We get a bug with text editor. 

When Chinese characters are typed with an input method, browser doesn't trigger key events as the Latin characters. As we rely on `onkeypress` event and `onkeydown` event to get the user input, the text editor failed to get Chinese characters.

We may need to monitor `oninput` to get user input instead.

**Comment by marco-c** [comment]
Fixed by #842.
