### ISSUE TITLE
Allow apps to exit

### ISSUE THREAD

**Issue by TimAbraldes** [andreasgal/j2me.js#866]
When the last foreground MIDlet stops running (i.e. the last Isolate calls `stop` as implemented in #744), we should close the app.

I'm not sure if FirefoxOS has a mechanism that allows apps to close themselves so this might not be possible.

**Comment by marco-c** [comment]
IIRC calling *window.close* closes the app

**Comment by TimAbraldes** [comment]
> IIRC calling window.close closes the app

When I tried that I got a "Scripts may not close windows that were not opened by script" error. I'll keep investigating though

**Comment by mykmelez** [comment]
> When I tried that I got a "Scripts may not close windows that were not opened by script" error. I'll keep investigating though

Maybe main.html needs to send a message to index.html via DumbPipe to close the window.

**Comment by marco-c** [comment]
Maybe you called it in the mozbrowser? I think you need to call it in the parent window, so with a DumbPipe

**Comment by TimAbraldes** [comment]
Gah, of course. I had forgotten about our index/main distinction.

However, I just tried adding this to index.js:

    DumbPipe.registerOpener("close", function(message, sender) {
      window.close();
    });

and calling that from code in native.js and I got the same error.

**Comment by marco-c** [comment]
Mmmmh, it used to work before (when I was playing with it to support updates).

**Comment by TimAbraldes** [comment]
Maybe it would work in the emulator and on device? I'm finding that it doesn't work in the browser, but I suppose that there's no meaningful way to "close" the emulator in the browser

**Comment by marco-c** [comment]
> Maybe it would work in the emulator and on device? I'm finding that it doesn't work in the browser, but I suppose that there's no meaningful way to "close" the emulator in the browser

I've tested in the simulator, so that's probably the reason!

**Comment by marco-c** [comment]
Fixed by https://github.com/andreasgal/j2me.js/pull/898
