### ISSUE TITLE
Don't directly draw to screen, but draw in an offscreen canvas and on screen only when refresh is called

### ISSUE THREAD

**Issue by marco-c** [andreasgal/j2me.js#875]

**Comment by marco-c** [comment]
I was trying to do this in https://github.com/marco-c/j2me.js/tree/offscreen_canvas.
Looks faster on desktop, but unfortunately not on mobile.

**Comment by marco-c** [comment]
Looks like the Display class is already drawing in an offscreen canvas, so this won't probably improve performance. It does help in removing the flickering.

**Comment by mykmelez** [comment]
> Looks like the Display class is already drawing in an offscreen canvas, so this won't probably improve performance.

Would it help to override the Display class natives responsible for flushing that buffer?

> It does help in removing the flickering.

Hmm, that's useful.

**Comment by marco-c** [comment]
I'm closing this since the Display class is already doing this and another PR fixed the flickering.

We might try overriding the Display methods though, since they're used a lot.
